name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout source code
        uses: actions/checkout@v3

      # Étape 2 : Se connecter au Docker Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construire l'image Docker
      - name: Build Docker Image with tags
        run: |
          docker build -t mohamed1780/api-user:latest .
          docker build -t mohamed1780/api-user:${{ github.sha }} .

      # Étape 4 : Pusher toutes les images Docker
      - name: Push Docker Image with tags
        run: |
          docker push mohamed1780/api-user:latest
          docker push mohamed1780/api-user:${{ github.sha }}
